/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
import { __core_private_DebugAppView__, __core_private_TemplateRef__, __core_private__ as r, __core_private_types__ as types } from '@angular/core';
export declare let _compiler_core_private_types: types;
export declare var isDefaultChangeDetectionStrategy: typeof r.isDefaultChangeDetectionStrategy;
export declare type ChangeDetectorStatus = typeof _compiler_core_private_types.ChangeDetectorStatus;
export declare var ChangeDetectorStatus: typeof r.ChangeDetectorStatus;
export declare var CHANGE_DETECTION_STRATEGY_VALUES: typeof r.CHANGE_DETECTION_STRATEGY_VALUES;
export declare var constructDependencies: typeof r.constructDependencies;
export declare type LifecycleHooks = typeof _compiler_core_private_types.LifecycleHooks;
export declare var LifecycleHooks: typeof r.LifecycleHooks;
export declare var LIFECYCLE_HOOKS_VALUES: typeof r.LIFECYCLE_HOOKS_VALUES;
export declare type ReflectorReader = typeof _compiler_core_private_types.ReflectorReader;
export declare var ReflectorReader: typeof r.ReflectorReader;
export declare type AppElement = typeof _compiler_core_private_types.AppElement;
export declare var AppElement: typeof r.AppElement;
export declare var CodegenComponentFactoryResolver: typeof r.CodegenComponentFactoryResolver;
export declare var AppView: typeof r.AppView;
export declare type DebugAppView<T> = __core_private_DebugAppView__<T>;
export declare var DebugAppView: typeof r.DebugAppView;
export declare var NgModuleInjector: typeof r.NgModuleInjector;
export declare type ViewType = typeof _compiler_core_private_types.ViewType;
export declare var ViewType: typeof r.ViewType;
export declare var MAX_INTERPOLATION_VALUES: typeof r.MAX_INTERPOLATION_VALUES;
export declare var checkBinding: typeof r.checkBinding;
export declare var flattenNestedViewRenderNodes: typeof r.flattenNestedViewRenderNodes;
export declare var interpolate: typeof r.interpolate;
export declare var ViewUtils: typeof r.ViewUtils;
export declare var VIEW_ENCAPSULATION_VALUES: typeof r.VIEW_ENCAPSULATION_VALUES;
export declare var DebugContext: typeof r.DebugContext;
export declare var StaticNodeDebugInfo: typeof r.StaticNodeDebugInfo;
export declare var devModeEqual: typeof r.devModeEqual;
export declare var UNINITIALIZED: typeof r.UNINITIALIZED;
export declare var ValueUnwrapper: typeof _compiler_core_private_types.ValueUnwrapper;
export declare type TemplateRef_<T> = __core_private_TemplateRef__<T>;
export declare var TemplateRef_: typeof r.TemplateRef_;
export declare type RenderDebugInfo = typeof _compiler_core_private_types.RenderDebugInfo;
export declare var RenderDebugInfo: typeof r.RenderDebugInfo;
export declare var EMPTY_ARRAY: typeof r.EMPTY_ARRAY;
export declare var EMPTY_MAP: typeof r.EMPTY_MAP;
export declare var pureProxy1: typeof r.pureProxy1;
export declare var pureProxy2: typeof r.pureProxy2;
export declare var pureProxy3: typeof r.pureProxy3;
export declare var pureProxy4: typeof r.pureProxy4;
export declare var pureProxy5: typeof r.pureProxy5;
export declare var pureProxy6: typeof r.pureProxy6;
export declare var pureProxy7: typeof r.pureProxy7;
export declare var pureProxy8: typeof r.pureProxy8;
export declare var pureProxy9: typeof r.pureProxy9;
export declare var pureProxy10: typeof r.pureProxy10;
export declare var castByValue: typeof r.castByValue;
export declare type Console = typeof _compiler_core_private_types.Console;
export declare var Console: typeof r.Console;
export declare var reflector: typeof _compiler_core_private_types.Reflector;
export declare var Reflector: typeof r.Reflector;
export declare type Reflector = typeof _compiler_core_private_types.Reflector;
export declare type ReflectionCapabilities = typeof _compiler_core_private_types.ReflectionCapabilities;
export declare var ReflectionCapabilities: typeof r.ReflectionCapabilities;
export declare type NoOpAnimationPlayer = typeof _compiler_core_private_types.NoOpAnimationPlayer;
export declare var NoOpAnimationPlayer: typeof r.NoOpAnimationPlayer;
export declare type AnimationPlayer = typeof _compiler_core_private_types.AnimationPlayer;
export declare var AnimationPlayer: typeof r.AnimationPlayer;
export declare type AnimationSequencePlayer = typeof _compiler_core_private_types.AnimationSequencePlayer;
export declare var AnimationSequencePlayer: typeof r.AnimationSequencePlayer;
export declare type AnimationGroupPlayer = typeof _compiler_core_private_types.AnimationGroupPlayer;
export declare var AnimationGroupPlayer: typeof r.AnimationGroupPlayer;
export declare type AnimationKeyframe = typeof _compiler_core_private_types.AnimationKeyframe;
export declare var AnimationKeyframe: typeof r.AnimationKeyframe;
export declare type AnimationStyles = typeof _compiler_core_private_types.AnimationStyles;
export declare var AnimationStyles: typeof r.AnimationStyles;
export declare type AnimationOutput = typeof _compiler_core_private_types.AnimationOutput;
export declare var AnimationOutput: typeof r.AnimationOutput;
export declare var ANY_STATE: string;
export declare var DEFAULT_STATE: string;
export declare var EMPTY_STATE: string;
export declare var FILL_STYLE_FLAG: string;
export declare var prepareFinalAnimationStyles: typeof r.prepareFinalAnimationStyles;
export declare var balanceAnimationKeyframes: typeof r.balanceAnimationKeyframes;
export declare var flattenStyles: typeof r.flattenStyles;
export declare var clearStyles: typeof r.clearStyles;
export declare var collectAndResolveStyles: typeof r.collectAndResolveStyles;
export declare var renderStyles: typeof r.renderStyles;
export declare type ViewMetadata = typeof _compiler_core_private_types.ViewMetadata;
export declare var ViewMetadata: typeof r.ViewMetadata;
export declare type ComponentStillLoadingError = typeof _compiler_core_private_types.ComponentStillLoadingError;
export declare var ComponentStillLoadingError: typeof r.ComponentStillLoadingError;
